# sorry for all the vars, there's no RPM
#
# basically, we download nexus3_tar_url to nexus3_tar_cache,
# then extract it under nexus3_home_parent to create nexus3_home...
#
nexus3_release: nexus-3.2.1-01
nexus3_tar_url: "http://download.sonatype.com/nexus/3/{{ nexus3_release }}-unix.tar.gz"
nexus3_tar_cache: "/root/.{{ nexus3_release }}-unix.tar.gz"

nexus3_home_parent: /opt
nexus3_home: "{{ nexus3_home_parent }}/{{ nexus3_release }}"
nexus3_user: nexus
